# Generated by Django 4.2.7 on 2024-01-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0004_carinventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
